Section contacts
MyshkoMykhailo/Reach-the-edge-ice-cream pull request #13
Opened 2022-01-16 11:00 UTC by saralidze87

2022-01-16 14:31 UTC, MyshkoMykhailo requested changes

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
в sprite є одна іконка - ./images/icons.svg#icon-vector (я мав попередити), і ти береш її в обох svg. кожній svg окремо ти даєш окремий клас, і фарбуєш в той чи інший колір через fill
розмір свг давай 6 * 10

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
тут  теж посилаємось на ./images/icons.svg#icon-vector, і теж через клас задаєш потрібний колір.
розмір свг давай 6 * 10

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +  <div class="container contacts__container">
зверни увагу, в мобільній версії в тебе в контейнера падінги не такі як у всіх - не 20px, а 50px, тож тобі треба в стилях задати щось типу
contacts .container {
@media screen and (max-width 767.5px) {
padding-left: 50px;
padding-right: 50px;
}
}

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 1280px) {
зміни точку брейкпойнта - має бути 768

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +          <li class="about-category__item list">Chicago
в тебе Chicago має бути в щось обернуто, і саме тому, в що ти це Chicago обернеш, ти задаєш стилі.

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +    margin-top: 25px;
не треба задавати першій li-шці марджин топ - це проти правил. так, у нас флекс, але відштовхувати марджином li - категорично неправильно - ти марджинами розштовхуєш тільки сусідів. а твоє CAFE - не сусід для твоєї лішки. задай краще марджин ботом 25px для category__name

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +    margin-top: -84px;
margin-top: -78px; for tab-version
margin-top: -102px; for desktop-version

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +    color: #907e82;
пропиши через змінну плз var(--section-text-second-color)

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +  &__weekdays {
тут можна скоротити кількість рядків (див нижче, дугий раз написано &__weekends {    )

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 768px) {
оці два медіазапити треба всунути в дужки для &__time, бо зараз ці медіазапити прописані для чогось іншого - для .schedule

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +      @include font(500, 16px, 1.83, 0.04em);
for tab-version font-size 14, line height 1.86

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +      @include font(500, 16px, 1.88, 0.04em);
line-height 1.86

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +    background-image: url('../images/pc/footer-picture.png');
1. Тобі треба перенести фонову картинку з секції на контейнер - вона має обмежену ширину 1920, тож вона повинна після 1920пікселів перестати тозтігуватись - це зробимо в контейнері лдя цієї секції (див нижче)
2. я залив дві нові картинки, правильні - contacts-bg@2x.png і contacts-bg.png, використай їх

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +    justify-content: center;
задай цьому контейнеру отаке:
 background-image: url('../images/pc/бла-бла-бла.png');
    background-position: center;
    background-size: contain;
і звісно, ще один фон через медіазапит.
і ще додай запит

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +      margin-bottom: 30px;
це медіазапит для 768px, а з 1280px марджин ботом 32
хоча б перенеси медіазапит з 1280 на 762, думаю, буде достатньо

2022-01-16 14:31 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +      margin-top: 14px;
margin-top: 14px; на 1280 px треба знов вернути на 10px

2022-01-16 18:03 UTC, saralidze87 commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
+

2022-01-16 18:50 UTC, saralidze87 commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
done 6*9

2022-01-16 18:50 UTC, saralidze87 commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
done 6*9

2022-01-16 18:51 UTC, saralidze87 commented on src/partials/contacts.html
> +  <div class="container contacts__container">
дякую, що зауважив ) зроблено!

2022-01-16 18:52 UTC, saralidze87 commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
зроблено 6*9

2022-01-16 18:52 UTC, saralidze87 commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
зроблено 6*9

2022-01-16 18:53 UTC, saralidze87 commented on src/partials/contacts.html
> +  <div class="container contacts__container">
зроблено:  padding-left: 50px;
  padding-right: 50px;
  @media screen and (min-width: 768px) {
    padding-left: 36px;
    padding-right: 36px;
  }
  @media screen and (min-width: 1280px) {
    padding-left: 115px;
    padding-right: 115px;

2022-01-16 18:53 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 1280px) {
виправлено)

2022-01-16 18:53 UTC, saralidze87 commented on src/partials/contacts.html
> +          <li class="about-category__item list">Chicago
обернула в <p>

2022-01-16 18:54 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +      @include font(500, 16px, 1.88, 0.04em);
done!

2022-01-16 18:54 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +    background-image: url('../images/pc/footer-picture.png');
Дякую, зроблено!

2022-01-16 18:55 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +    justify-content: center;
зроблено, дякую)))                    background-color: var(--section-background-coloured-color);
    background-image: url('../images/pc/contacts-bg.png');
    background-repeat: no-repeat;
    background-position: top;
    background-size: auto;
    @media (min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx) {
      background-image: url('../images/pc/contacts-bg@2x.png');

2022-01-16 18:56 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +      margin-bottom: 30px;
зробила, як треба, дякую!

2022-01-16 18:56 UTC, saralidze87 commented on src/sass/layout/_contacts.scss
> +      margin-top: 14px;
Є

2022-01-17 09:56 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +  <div class="container contacts__container">
можна було коротше, але працює )

2022-01-17 09:56 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +            <svg class="svg" width="8" height="8">
ок

2022-01-17 09:57 UTC, MyshkoMykhailo commented on src/sass/layout/_contacts.scss
> +  @media screen and (min-width: 1280px) {
добре

2022-01-17 09:57 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +  <div class="container contacts__container">
можна було коротше, проте працює, то ОК!

2022-01-17 09:58 UTC, MyshkoMykhailo commented on src/partials/contacts.html
> +          <li class="about-category__item list">Chicago
добре!

2022-01-17 10:17 UTC, MyshkoMykhailo approved these changes

2022-01-17 10:17 UTC, merged